enable nullable for commands
nunit/nunit pull request #4180
Opened 2022-09-13 10:40 UTC by SimonCropp

2022-09-14 08:13 UTC, manfred-brands requested changes
The original design of the protected field that needs to be set in derived classes is not the best and can be done better, either using a abstract method or a constructor parameter.

2022-09-14 10:26 UTC, SimonCropp commented on src/NUnitFramework/framework/Internal/Commands/BeforeAndAfterTestCommand.cs
> +        protected Action<TestExecutionContext> AfterTest = null!;
wouldnt that be a breaking change?

2022-09-14 11:31 UTC, manfred-brands commented on src/NUnitFramework/framework/Internal/Commands/BeforeAndAfterTestCommand.cs
> +        protected Action<TestExecutionContext> AfterTest = null!;
Yes and even though the classes are in an internal namespace they are still public.

So let stick to exisiting design and simply declare the Action fields as nullable. They are already checked for null before use.

2022-09-14 12:17 UTC, SimonCropp commented on src/NUnitFramework/framework/Internal/Commands/BeforeAndAfterTestCommand.cs
> +        protected Action<TestExecutionContext> AfterTest = null!;
done

2022-10-03 23:39 UTC, SimonCropp commented
this one should be good to go

2022-10-07 19:49 UTC, SimonCropp commented
@manfred-brands 

> The original design of the protected field that needs to be set in derived classes is not the best and can be done better, either using a abstract method or a constructor parameter.

i would prefer to do that in another PR

2022-10-09 09:32 UTC, SimonCropp commented
bump

2022-10-09 17:29 UTC, stevenaw commented on src/NUnitFramework/framework/Internal/Commands/SetUpTearDownCommand.cs
> +            BeforeTest = setUpTearDown.RunSetUp;
👍 for this simplification

2022-10-09 17:31 UTC, stevenaw commented on src/NUnitFramework/framework/Internal/Commands/ConstructFixtureCommand.cs
> +                    context.TestObject = Test.Fixture ??= typeInfo.Construct(((TestSuite)Test).Arguments);
It took me a bit to think through the possibilities here to ensure this was still the same logic but it seems sound

2022-10-09 17:35 UTC, stevenaw approved these changes
Thank you for this @SimonCropp !
LGTM but I'd appreciate a second pair of eyes for review before merging.

2022-10-10 12:36 UTC, SimonCropp commented
@stevenaw who would be best to do that?

2022-10-10 21:07 UTC, stevenaw commented
Oh, I see @manfred-brands already had a look.

2022-10-10 21:07 UTC, merged