Accumulate further failures if any on AssertMultiple instead of throwing
nunit/nunit pull request #4313
Opened 2023-03-16 20:42 UTC by sdelarosbil

Closes #4264 

This implements the suggested solution. It turns out it was suitable to fix this issue. We still throw on the first fail, but any further one is only cumulated in case one appears after a catch block or in the teardown.

2023-03-17 02:02 UTC, mr-russ commented
Is there a way to add a test to verify it will stay working in the future?
Should this get a 3.13-dev fix if it's accepted?

2023-03-17 14:42 UTC, sdelarosbil commented
> Is there a way to add a test to verify it will stay working in the future? Should this get a 3.13-dev fix if it's accepted?

I'm actually not sure how you can reliably test this: you expect an assert to fail, but lines after to be executed. I don't think I am knowledgeable enough on setting up such a test because the best I could get on my hand was expecting a failure shaped in a certain way in the console, I just don't know how you make a test for this.

As for 3.13, either works, it's a low priority issue.

2023-03-22 03:41 UTC, mr-russ commented
I looked at how the existing AssertMultiple does its testing, and https://github.com/nunit/nunit/blob/master/src/NUnitFramework/tests/Assertions/AssertMultipleTests.cs#L124 suggests that making an explicit test that produces what you are expecting is probably the best method.  Even if only run manually for checking it's reproducible and in the code and can be checked at any time.

2023-03-24 00:54 UTC, stevenaw commented on src/NUnitFramework/framework/Assert.cs
> +            var oldCount = context.CurrentResult.AssertionResults.Count;
Thanks for having added these

2023-03-24 01:08 UTC, stevenaw requested changes
Thanks for the quick fix you applied here @sdelarosbil . The fix itself looks good, but can we add [this repro](https://github.com/nunit/nunit/issues/4264#issuecomment-1336297152) as a non-explicit test so that it may fail if a future PR accidentally undoes your bugfix?

2023-03-27 15:26 UTC, sdelarosbil commented on src/NUnitFramework/tests/Assertions/AssertMultipleTests.cs
> +    public class MultipleAssertFailureAccumulationDemo
I tried to add it changing the console writeline to Assert.Warn, but it doesn't work due to the stacktrace being null.

2023-04-03 09:08 UTC, OsirisTerje commented
@sdelarosbil Can you copy-add in the test that @stevenaw suggested?   We could then merge this PR immediately after that.  Nothing else seems to be missing in this PR.

2023-04-03 14:32 UTC, sdelarosbil commented
> @sdelarosbil Can you copy-add in the test that @stevenaw suggested? We could then merge this PR immediately after that. Nothing else seems to be missing in this PR.

Yes, I tried to add the test, the problem is it's not possible as far as I could see to make it not fail.

The test is designed to fail in a specific way such that something after an assert still executes. If I copy verbatim, the test fail, but in an expected way which I didn't find a way to turn it into a success. If there's something I am missing, please let me know, but I am confused how the test should be implemented to not have that happen.

2023-04-06 19:07 UTC, merged

2023-04-06 19:07 UTC, OsirisTerje commented
@sdelarosbil Accepted, we'll move the testing out as a separate issue.   @stevenaw  or I can try to get it working.  
The issue is #4331