WIP: Issue4413 caller argument expression
nunit/nunit pull request #4430
Opened 2023-07-22 10:58 UTC by manfred-brands

@OsirisTerje I see a problem, the compiler cannot distinguish between:

```csharp
Assert.That(actual, constraint, [CAE] string actualExpression, [CAE] string constraintExpression)
{}
Assert.That(actual, constraint, string? message, [CAE] string actualExpression =  "", [CAE] string constraintExpression = "")
{}
```
When calling it like:
```
Assert.That(actual, constraint, message)
```

Because it matches both.

2023-07-22 11:02 UTC, manfred-brands commented
See here:
![image](https://github.com/nunit/nunit/assets/8655218/630af383-3452-44e0-b466-01d1c3fbe17b)

It thinks we passed an `actualMessage` not a `message`.

2023-07-22 11:53 UTC, OsirisTerje commented
Got the same.  I changed the nullable message strings into non-null.  That sølvet it.   Suggest you merge my cae branch into your.  I can merge back again tomorrow to get your changes in.

2023-07-23 20:29 UTC, OsirisTerje commented
@manfred-brands  Partially merged this into the CallerArgumentExpression branch, PR #4427 

We should handle conditional formatting as an addition afterwards.  I am not sure why we actually need it btw, but perhaps some discussion I have missed?

There are no overloads that don't compile now.

2023-07-23 22:47 UTC, manfred-brands commented
> We should handle conditional formatting as an addition afterwards. I am not sure why we actually need it btw, but perhaps some discussion I have missed?

String formatting is a very expensive operation. Doing this for every unit tests will make tests run much slower. I'll see if I can create a benchmark test quantifying this.

2023-07-24 03:34 UTC, manfred-brands commented
@OsirisTerje Once I noticed that you removed the overloads with no _message_ parameter, I could finish mine.
Seeing what you did, I fixed the nunit test asserting message contains from 'Is.EqualTo' into 'Does.Contain'.
I added nunit tests to assert that the message contains the _actual_ and _constraint_ expressions.

Note that there is no conditional on nunit462/net6.0. the CAE works for all TargetFrameworks.

2023-07-24 09:22 UTC, OsirisTerje requested changes

2023-07-24 09:22 UTC, OsirisTerje commented on src/NUnitFramework/tests/Attributes/LifeCycleAttributeTests.cs
> +            Assert.That(result.ResultState.Status, Is.EqualTo(TestStatus.Passed), (NUnitString)result.Message);
Is the typecast needed?

2023-07-24 09:33 UTC, manfred-brands commented on src/NUnitFramework/framework/Assert.ThatAsync.cs
> +#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment (but other parameters do)
I do agree about the clutter. I had initially thought of only doing one at the top of file as well.
The reason I didn't is that we would then miss errors if a real field was added to a method without corresponding documentation. If you think that won't be an issue I can reduce to a single disable.

2023-07-24 09:43 UTC, manfred-brands commented on src/NUnitFramework/framework/Properties/AssemblyInfo.cs
> +[assembly: AssemblyTitle("NUnit Framework (.NET 6.0-windows)")]
Indeed forgotten to remove. Also removed NETSTANDARD2_0 and more from CommonAssembly.cs

2023-07-24 09:45 UTC, manfred-brands commented on src/NUnitFramework/tests/Attributes/LifeCycleAttributeTests.cs
> +            Assert.That(result.ResultState.Status, Is.EqualTo(TestStatus.Passed), (NUnitString)result.Message);
Not anymore. Removed.

2023-07-24 09:55 UTC, manfred-brands commented on src/NUnitFramework/framework/Assert.cs
> +        internal static string? ExtendedMessage(string methodName, string? message, string actualExpression, string constraintExpression)
The return type indeed not.  Changed.

The _message_ comes from the _getExceptionMessage` overloads which are declared as `Func<string?>`.
Also there are some NUnit tests (e.g. `LifeCycleAttributeTest`) that pass in `result.Message` which is also declared `string?`.
If we want to change all that, I would do that in a separate PR.

2023-07-24 09:59 UTC, manfred-brands commented on src/NUnitFramework/framework/NUnitString.cs
> +            _message = message;
We can change it, depending on the outcome above.
If `null` is still a valid parameter, it is better to leave it as that then add an extra conditional.
The place where it is relevant (`Assert.ExtendedMessage`) uses `string.IsNullOrEmpty` so can deal with either.

2023-07-24 10:01 UTC, manfred-brands commented on src/NUnitFramework/framework/Assert.ThatAsync.cs
> +            [CallerArgumentExpression(nameof(code))] string actualExpression = "",
I didn't get the warnings. Although intellisense didn't want to help me here.
The language version is dependent on the compiler, not the runtime. As we use the NET7.0 SDK, we can use LangVersion11.

2023-07-24 10:11 UTC, manfred-brands commented on src/NUnitFramework/framework/Assert.ThatAsync.cs
> +            [CallerArgumentExpression(nameof(code))] string actualExpression = "",
Actually setting the LangVersion to 11 causes the intellisense to work.

2023-07-24 10:13 UTC, manfred-brands commented on src/NUnitFramework/framework/Assert.ThatAsync.cs
> +#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment (but other parameters do)
Changed this in a separate commit. Depending on your answer above we can remove or keep it.

2023-07-24 13:35 UTC, OsirisTerje commented on src/NUnitFramework/framework/NUnitString.cs
> +            _message = message;
Sounds good.  
The more nulls we can fix up, the better.
I added that as a task in #4431

2023-07-24 14:51 UTC, OsirisTerje approved these changes

2023-07-24 14:52 UTC, merged