Reduces allocations for TestResult.AddToXml
nunit/nunit pull request #4460
Opened 2023-08-14 10:24 UTC by pepelev

Hi!

When `Output` is not empty there are two allocations of same string. This pull request eliminates it.
Also content of `Output` possibly may be changed between acquisitions of same lock on `OutWriter` twice, which can be misleading.

2023-08-14 11:45 UTC, pepelev commented
@dotnet-policy-service agree

2023-08-15 08:59 UTC, pepelev commented on src/NUnitFramework/framework/Internal/Results/TestResult.cs
> +            if (outputContent.Length > 0)
Putting the check inside the method has two drawbacks:

1. It breaks existing structure
Now end of the `AddToXml` method has the following pattern:
```
if (need-to-write1)
   Write1();
   
if (need-to-write2)
   Write2();
   
...
```
It turns out that some write operations guarded by external condition, while others maintain the condition by themselves. Such a difference increases diversity and, therefore, complicates the code.

2. Name `AddOutputElement` will become misleading
The method stands for adding output element, but with the inner check in some cases adding will not happen. This discrepancy between the method name and the actual behavior confuses the reader.
We could name the method as `AddOutputElementIfNotEmpty`, but this makes the name long and adds a second responsibility to the method.

> It looks like `AddAssertionsElement` has the same issue

Nice catch!

2023-08-15 09:14 UTC, pepelev commented
I am making similar changes to the 'AddAssertionsElement` method and others

2023-08-15 10:24 UTC, OsirisTerje commented
We have a Benchmark project, it would be nice if this was used to ensure this is change that does something that is significant.
Also, the changes must be covered by either existing or new unit test.
There are also no issue being referred to, so this is an ad-hoc change.

2023-10-14 19:24 UTC, lahma commented
Looks like the one-time evaluation of `Output` and `StackTrace` are the most valuable changes here, others are more like syntactic cleanup if I understand correctly. From reading the code I would say these are quite safe changes to consider.

2023-10-15 04:05 UTC, manfred-brands requested changes
I don't like the introduction of the _empty property pattern_: `is { }` especially when the types are known. Either drop these unrelated changes completely or convert to the suggested versions with strict types.

2024-01-07 08:08 UTC, OsirisTerje commented
@pepelev Are you going to fix the above comments?

2024-02-29 10:26 UTC, closed without merging