Switch to using license expression
nunit/nunit pull request #4617
Opened 2024-02-07 08:52 UTC by lahma

By using license expression it will show up correctly on nuget.org and helps license validators/checkers to know what is the exact license type. Usually you have this in csproj file producing the nuspec, but I checked what kind of file is generated with `<PackageLicenseExpression>MIT</PackageLicenseExpression>`. The package will also still contain the license file.

Currently on [nuget.org](https://www.nuget.org/packages/NUnit):

![image](https://github.com/nunit/nunit/assets/171892/46c668e8-4ba5-4aa8-ada0-9aa0e27f1b9a)

Ideally like for [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json):

![image](https://github.com/nunit/nunit/assets/171892/108de37d-1d1c-471b-9217-c038691884e0)

2024-02-07 11:36 UTC, OsirisTerje commented on nuget/nunitlite/nunitlite.nuspec
> +    <licenseUrl>https://licenses.nuget.org/MIT</licenseUrl>
Is this url correct?  Without it, the license points to this URL anyway, see NUnit3TestAdapter, and it then doesn't have the fields filled out.   Do you have an another package as an example?

2024-02-07 12:11 UTC, OsirisTerje requested changes
Not sure this is the way to go, and if we do it, it must have the year info and owner info.

2024-02-08 17:36 UTC, lahma commented
Sorry, I need to get back to this a bit later. Generally what you see is generated and "machine readable" so what should be advertised as the license and as an agreement.

Based on the general license notes the names of people seem to be a bit auxiliary to the actual license. They seem to mainly provide context about the work that has been done when permissive licenses are being used. So for example GitHub shows info as "MIT license" regardless of who has been named the actual person that did the hard work.

From NUnit repo the license "headers" GitHub provides:

![image](https://github.com/nunit/nunit/assets/171892/2a901734-4bbe-4ac8-9119-83b2de8dedc0)

And the right-hand bar

![image](https://github.com/nunit/nunit/assets/171892/180a567f-c8b8-4bd1-8f87-606af30f63e1)

I hope I don't indicate I want to change the license, I would want just to provide the general go/no-go decision for anyone browsing the nuget.org. OK fair, I'm trying to make the license checkers happy 😉

2024-02-17 09:39 UTC, lahma commented
I force-pushed a fix to point to GitHub repository's license file. This hopefully still keeps license analyzers happy.

2024-02-17 09:54 UTC, lahma commented
...and it doesn't work...

```
========================================
PackageFramework
========================================
Attempting to build package from 'nunit.temp.nuspec'.
The licenseUrl and license elements cannot be used together.
An error occurred when executing task 'PackageFramework'.
```

So package needs to have just the expression and license can be part of the regular root package location, which it already is.

2024-02-17 10:30 UTC, OsirisTerje commented
About the license, it is not about showing the MIT license symbol, but when you go to that license, it has template fields that are not filled in - for year and names.

2024-02-17 10:36 UTC, lahma commented
Yes I understand the concern, but Microsoft has the same situation: https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/8.0.0 , same kind of template link there but the actual package contains `LICENSE.txt` : https://nuget.info/packages/Microsoft.Extensions.DependencyInjection/8.0.0 .

I believe the expression of indicator of license format and restrictions and then the actual license is/can be part of the package and of course part of original repository which holds more details. So as a consumer if I see that it's MIT/Apache-2.0/BSD I know where I'm getting into and I know I just need to be ready to show the project's license which includes the actual authors and copyrights but I don't need to worry about redistribution rights etc.

2024-02-17 10:40 UTC, lahma commented
For reference I have [this fairly popular NuGet package](https://www.nuget.org/packages/Quartz) with same kind of template shown on NuGet.org, I don't mind - I still have the "actual license" that follows the template and has my name and year on it.

2024-02-17 18:25 UTC, lahma commented
And as an another example, [NUnit3TestAdapter uses the expression and doesn't package the license with the package](https://nuget.info/packages/NUnit3TestAdapter/4.5.0).

2024-02-17 19:29 UTC, OsirisTerje commented
Got me there :-)

2024-02-17 19:43 UTC, OsirisTerje approved these changes
Have no choice anymore :-)

2024-02-17 19:43 UTC, merged

2024-02-17 21:28 UTC, lahma commented
Thanks for accepting the change,  I hope it will be for the common good 🙂