Generic EqualConstraint
nunit/nunit pull request #4844
Opened 2024-09-28 00:16 UTC by stevenaw

Remade PR https://github.com/nunit/nunit/pull/4456
Contributes to https://github.com/nunit/nunit/issues/53

2024-09-28 11:02 UTC, manfred-brands requested changes
@stevenaw I am sorry,  but I'm still not convinced this does help us in anyway.

The implementation doesn't increase type safety.
It still allows `Assert.That("Apple", Is.EqualTo(5))`
It also doesn't reduce boxing for numerics as the `NUintEqualityAdapter.AreEqual` drops to `object` quickly.

Sorry.

2024-09-28 12:01 UTC, stevenaw commented on src/NUnitFramework/framework/Constraints/EqualConstraint{T}.cs
> +            return (EqualConstraint<T>)base.Using(comparer);
This was needed to fix an overload resolution issue in the tests

2024-09-28 12:01 UTC, stevenaw commented on src/NUnitFramework/framework/Constraints/EqualConstraint{T}.cs
> +        }
This was needed to fix an overload resolution issue in the tests

2024-09-28 12:01 UTC, stevenaw commented on src/NUnitFramework/framework/Constraints/EqualConstraint{T}.cs
> +        }
This was needed to fix an overload resolution issue in the tests

2024-09-28 12:02 UTC, stevenaw commented on src/NUnitFramework/framework/Constraints/EqualConstraint{T}.cs
> +        }
This was needed to fix an overload resolution issue in the tests

2024-09-28 12:02 UTC, stevenaw commented on src/NUnitFramework/framework/Constraints/EqualConstraint{T}.cs
> +        }
This was needed to fix an overload resolution issue in the tests

2024-09-28 12:04 UTC, stevenaw commented on src/NUnitFramework/framework/Constraints/EqualConstraint{T}.cs
> +            _tolerance = new Tolerance(amount!);
Unfortunately, we must derive from `EqualConstraint` to avoid binary breaking consumers as it is the current return type of `Is.EqualTo()`

2024-09-28 12:05 UTC, stevenaw commented on src/NUnitFramework/framework/Constraints/EqualConstraint{T}.cs
> +            return (EqualConstraint<T>)base.Using(comparer);
Thanks, I'll take a closer look ☺️ 
Most of the things in this PR were done to allow incremental improvements without incurring breaking changes, but I can't recall the story here. I maybe missed an opportunity

2024-09-28 12:08 UTC, stevenaw commented on src/NUnitFramework/framework/Constraints/EqualConstraint{T}.cs
> +                bool isSuccess = _comparer.AreEqual(_expected, a, ref _tolerance);
The aim isn't to reduce boxing in this PR per se, but to start getting a public strongly typed API. Eventually, once a few more constraints have strong typing, it'll be easier to tackle reducing boxing

2024-09-28 12:48 UTC, stevenaw commented on src/NUnitFramework/framework/Constraints/EqualConstraint{T}.cs
> +        }
I'll double check this one. It "may" be required to keep some formatting on a message in the tests, but that could've also been caused by an earlier attempt during development.

2024-09-28 12:53 UTC, stevenaw commented
Thanks for the review @manfred-brands I'll go back and check a few things. Many of the changes here are made to support incremental, non-breaking changes rather than a "big-bang" rewrite all at once.

Unfortunately, strong-typing `expected` and `actual` at the `Assert.That` level will require strong-typing the constraint resolver+builder, which is significantly more work than intended for here. That change would be tough to do non-breaking, but one I'd like to try my hand at after getting the following other pieces in place in their own respective PRs 
- equivalency constraints
- collection constraints
- internal comparers

2024-09-28 13:02 UTC, manfred-brands commented
@stevenaw I know it is hard. I had several starts myself where I started small but then dug myself in a hole.

2024-11-04 21:28 UTC, stevenaw commented
@manfred-brands @OsirisTerje 
We made the decision in https://github.com/nunit/nunit/pull/4848 to change the return type under the controls that we do not modify the original return type in order to mitigate binary compatibility issues. Are there any concerns if I were to follow the same approach here?

2024-11-07 03:21 UTC, stevenaw commented
@manfred-brands you may be getting ahead of me here. My intent with the PR is much smaller, primarily to just add a new `EqualsConstraint<T> : Constraint` and not touch the resolvers or to get into which cases null is appropriate for or not. My thinking is that it would compliment the PRs you've already put up rather than replace by covering the last few % of use cases not already covered by your primitives overloads: namely composite reference or value types.

The hope is that this could give us a foothold to eventually pass generic typing down into some of the framework intervals to bring type-safety a bit lower into the framework. Getting those internals type-safe will be important to eventually getting generics working with the collection-based constraints

2024-11-11 21:34 UTC, stevenaw commented
It feels like there's a few different ideas here. I'm going to close this PR for now but keep the branch so that we can continue discussing the approach in the issue. Type-safety will still be added for the majority of callsites via https://github.com/nunit/nunit/pull/4882 so this issue + PR would likely focus primarily on the remaining "composite types" use cases

2024-11-11 21:34 UTC, closed without merging