Add a .NET 8.0 target
nunit/nunit pull request #4884
Opened 2024-11-13 10:25 UTC by manfred-brands

Works toward #4857

This adds the .NET 8.0 target. So that if users that are not allowed to use end-of-life frameworks due to lack of security updates can the .NET8.0 binaries.

2024-11-14 11:52 UTC, mikkelbu approved these changes
Looks good - only comments and questions from me 👍

2024-11-14 11:52 UTC, mikkelbu commented on src/NUnitFramework/framework/Internal/InvalidDataSourceException.cs
> +#endif
Just suggestions. Should we move the usings outside the namespace? (and perhaps move `System.Runtime.Serialization`  down to the sole purpose, so we avoid having two `!NET8_0_OR_GREATER` blocks ?

EDIT: I can see that we do it differently in many of the `...Exception` files, so I'm also happy with the current solution (to keep the fix as small as possible)

2024-11-14 11:52 UTC, mikkelbu commented on src/NUnitFramework/nunitlite/Options.cs
> +#endif
Why is this need now ?

2024-11-14 11:52 UTC, mikkelbu commented on src/NUnitFramework/nunitlite/Options.cs
>  #if !NET6_0_OR_GREATER
Doesn't `#if !NET6_0_OR_GREATER` imply `#if !NET8_0_OR_GREATER` ? 
Or is this to to anticipate when we remove the .NET6 target ?

2024-11-19 20:00 UTC, OsirisTerje requested changes
We need to add the .net 8 bits to the nunit.nuspec file, otherwise the bits don't go into the nupkg.

2024-11-20 03:26 UTC, manfred-brands commented
> We need to add the .net 8 bits to the nunit.nuspec file, otherwise the bits don't go into the nupkg.

Thanks @OsirisTerje 

I forgot and to ensure nobody will forget it again, I added a nunit test to verify proper file references in .nuspec files.
Similar to the one you added for dependencies.

The bulk of the size is the 3 copies of the .xml files 1.2MB per target.
They are 99% the same with a few TFM specific APIs.
I tired to put only one of the in lib/any but it then doesn't seem to be picked up.
Searching the net didn't result in any solutions.

2024-11-25 19:37 UTC, OsirisTerje approved these changes

2024-11-25 19:37 UTC, OsirisTerje commented
Lgtm,  @manfred-brands : can we merge ?

2024-11-26 01:45 UTC, merged